source 'https://rubygems.org'

gem 'activesupport'
gem 'allure-cucumber'
gem 'parallel_split_test'
gem 'parallel_tests'
gem 'rake'
gem 'reek'
gem 'cucumber'
gem 'rspec'
gem 'rubocop'
gem 'ruby_raider', '~> 0.8.0'
gem 'selenium-webdriver'
gem 'watir'
